sudo: required
services:
    -docker

before_install:
    - docker build -t claudiocoder/multi-client -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true claudiocoder/multi-client npm test

after_success:
    - docker build -t claudiocoder/multi-client ./client
    - docker build -t claudiocoder/multi-nginx ./nginx
    - docker build -t claudiocoder/multi-server ./server
    - docker build -t claudiocoder/multi-worker ./worker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push claudiocoder/multi-client
    - docker push claudiocoder/multi-nginx
    - docker push claudiocoder/multi-server
    - docker push claudiocoder/multi-worker